config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "feeds#index"

  get :privacy_policy, to: "static_pages#privacy_policy"
  get :contact, to: "static_pages#contact"
  post :messages, to: 'static_pages#messages'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get :subcategory_options, to: "deals#subcategory_options"

  resources :feeds, only: [:index]
  resources :deals do
    resources :comments, only: :create
  end

    get :men, to: "deals#men"
    get :women, to: "deals#women"
    get :beauty, to: "deals#beauty"

  resources :retailers, only: [:index, :show] do
    collection do
      post :import
    end
  end

  resources :articles, only: [:index, :create]
  get :get_article, to: "articles#get_article"

  namespace :admin do
    resources :deals do
      collection do
        post :import
        get :edit_multiple
        put :update_multiple
      end
    end
    resources :retailers do
      collection do
        post :import
      end
    end
    resources :publishers do
    end
  end

end

app/models/retailer.rb
class Retailer < ActiveRecord::Base
	has_many :deals
	has_and_belongs_to_many :categories

	validates :name, presence: true
	validates :host_url, presence: true
	validates :brief_description, presence: true

	mount_uploader :favicon, PictureUploader
	mount_uploader :logo, PictureUploader
	mount_uploader :cover, PictureUploader

	extend FriendlyId
	friendly_id :name, use: :slugged


	acts_as_xlsx


	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item = find_by_id(row["id"]) || new
			item.attributes = row.to_hash.slice(*self.column_names)
			next if item.name.nil? || item.host_url.nil? || item.brief_description.nil?
			item.save!
			item.update_attributes(category_ids: row["category_ids"]) if row["category_ids"].present?
		end
	end
end

app/controllers/admin/retailers_controller.rb
class Admin::RetailersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin


  def index
    if params[:category].present?
      @retailers = Retailer.joins(:categories).where("categories.name = ?", params[:category])
      @retailer_type = params[:category]
    else
      @retailers = Retailer.all
    end
    respond_to do |format|
          format.html
          format.csv { send_data @retailers.to_csv, filename: "retailers-#{Date.today}.csv"}
          format.xlsx
        end
  end

  def new
    @retailer = Retailer.new
  end

  def import
      Retailer.import(params[:file])
      flash[:notice] = 'File has been imported'
      redirect_to retailers_path
    end


  def create
    @retailer = Retailer.create(retailer_params)
    if @retailer.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @retailer = Retailer.friendly.find(params[:id])
    return render_not_found if @retailer.blank?
  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end

  def update
    @retailer = Retailer.friendly.find(params[:id])
    return render_not_found if @retailer.blank?
    @retailer.update_attributes(retailer_params)

    if @retailer.valid?
      redirect_to edit_admin_retailer_path(@retailer)
    else
      return render_not_found(:unprocessable_entity)
    end
  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end

  def destroy
    @retailer = Retailer.friendly.find(params[:id])

    return render_not_found if @retailer.blank?
    @retailer.destroy
    redirect_to root_path
  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end

  private

  def retailer_params
    params.require(:retailer).permit(:name, :host_url, :part_url, :brief_description, :html_meta_description, 
      :description, :internal_notes, :admin_notes, :support_notes, :search_keywords, :facebook_url,
      :instagram_url, :favicon, :logo, :cover, :category_id, {category_ids: []}, :merchant_id, :strap_line, :tracking_link,
      :remote_logo_url)
  end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

	def index
		if params[:category].present?
			@retailers = Retailer.joins(:categories).where("categories.name = ?", params[:category]).order(:name)
			@retailer_type = params[:category]
		else
			@retailers = Retailer.all
		end
	end

	def show
		@retailer = Retailer.friendly.find(params[:id])
		return render_not_found if @retailer.blank?
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end


	private

	def retailer_params
		params.require(:retailer).permit(:name, :host_url, :part_url, :brief_description, :html_meta_description, 
			:description, :internal_notes, :admin_notes, :support_notes, :search_keywords, :facebook_url,
			:instagram_url, :favicon, :logo, :cover, :category_id, {category_ids: []}, :merchant_id, :strap_line)
	end
end

app/helpers/admin/retailers_helper.rb
module Admin::RetailersHelper
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/admin/retailers/edit.html.erb
<div class="container">
    <h1>Edit <%= @retailer.name %></h1>

    <%= simple_form_for [:admin, @retailer] do |f| %>
        <%= f.input :name %>
    	<%= f.input :host_url %>
        <%= f.input :tracking_link %>
        <%= f.input :part_url %>
        <%= f.input :brief_description %>
        <%= f.input :strap_line %>
        <%= f.input :html_meta_description %>
        <%= f.input :description %>
        <%= f.input :internal_notes %>
        <%= f.input :admin_notes %>
        <%= f.input :support_notes %>
        <%= f.input :search_keywords %>
        <%= f.input :facebook_url %>
        <%= f.input :instagram_url %>
        <%= f.input :favicon %>
        <%= image_tag @retailer.logo_url %>
        <%= f.input :logo %>
        <%= f.input :cover %>
        <%= f.submit 'Update' %>
    <% end %>
</div>

app/views/admin/retailers/index.html.erb
<div class="container">
  <% if current_user.try(:admin?) %>
    <div>
      Export Retailers to: <%= link_to "CSV", admin_retailers_path(format: 'csv') %> | <%= link_to "Excel", admin_retailers_path(format: 'xlsx') %>

          
      <%= form_tag import_admin_retailers_path, multipart: true do %>
        <%= file_field_tag :file, accept: 'text/csv' %>
        <%= submit_tag "Import Retailers" %>
      <% end %>
    </div>
  <% end %>

  <br />
  <%= link_to 'Add new retailer', new_admin_retailer_path, class: 'btn' %>
  <br />


  <table>
    <tr>
      <th>Retailer name</th>
    </tr>
    <% @retailers.each do |retailer| %>
    <tr>
      <td><%= link_to retailer.name, edit_admin_retailer_path(retailer) %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/retailers/new.html.erb
<div class="container">
    <h1>New Retailer</h1>

    <%= simple_form_for [:admin, @retailer] do |f| %>
      <%= f.input :name %>
      <%= f.input :host_url %>
      <%= f.input :tracking_link %> 
        <%= f.input :part_url %>
        <%= f.input :brief_description %>
        <%= f.input :strap_line %>
        <%= f.input :html_meta_description %>
        <%= f.input :description %>
        <%= f.input :merchant_id %>
        <%= f.input :internal_notes %>
        <%= f.input :admin_notes %>
        <%= f.input :support_notes %>
        <%= f.input :search_keywords %>
        <%= f.input :facebook_url %>
        <%= f.input :instagram_url %>
        <%= f.input :favicon %>
        <%= f.input :remote_logo_url %>
        <%= f.input :cover %>
        <%= f.submit 'Add' %>
    <% end %>
</div>