config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "feeds#index"

  get :privacy_policy, to: "static_pages#privacy_policy"
  get :contact, to: "static_pages#contact"
  post :messages, to: 'static_pages#messages'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get :subcategory_options, to: "deals#subcategory_options"

  resources :feeds, only: [:index]
  resources :deals do
    resources :comments, only: :create
  end

    get :men, to: "deals#men"
    get :women, to: "deals#women"
    get :beauty, to: "deals#beauty"

  resources :retailers, only: [:index, :show] do
    collection do
      post :import
    end
  end

  resources :articles, only: [:index, :create]
  get :get_article, to: "articles#get_article"

  namespace :admin do
    resources :deals do
      collection do
        post :import
        get :edit_multiple
        put :update_multiple
      end
    end
    resources :retailers do
      collection do
        post :import
      end
    end
    resources :publishers do
    end
  end

end

app/models/deal.rb
class Deal < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	validates :title, :message, :deeplink, presence: true
	validates :picture, presence: true

	belongs_to :user
	belongs_to :retailer
	belongs_to :subcategory
	belongs_to :gender

	has_many :comments

	acts_as_xlsx

	scope :from_now, -> { self.where('starts >= ?', DateTime.now) }

	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item = find_by_id(row["id"]) || new
			item.attributes = row.to_hash.slice(*self.column_names)
			# item.title = "#{item.advertiser} #{item.starts.strftime('%d-%m-%Y')}" if item.starts.present?
			item.save!
		end
	end
end

app/controllers/admin/deals_controller.rb
class Admin::DealsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

  def index
    @deals = Deal.all
    respond_to do |format|
        format.html
        format.csv { send_data @deals.to_csv, filename: "deals-#{Date.today}.csv"}
        format.xlsx
    end
  end

	def import
      Deal.import(params[:file])
      flash[:notice] = 'File has been imported'
      redirect_to admin_deals_path
    end
    
	def edit_multiple
     	@deals = Deal.where(id: deal_params[:deal_ids])
     	return render_not_found if @deals.blank?
     	return render_not_found(:forbidden) if !current_user.admin?
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def update_multiple
		@deals = Deal.friendly.update(params[:deals].keys, params[:deals].values)
		return render_not_found(:forbidden) if !current_user.admin?
		
		@deals.reject! { |deal| deal.errors.empty? }
		if @deals.empty?
			redirect_to admin_deals_path
		else
			render "edit_multiple"
		end
	end

  def new
    @deal = Deal.new
  end

  def create
    @deal = current_user.deals.create(deal_params)
    if @deal.valid?
      redirect_to admin_deals_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @deal = Deal.friendly.find(params[:id])
    return render_not_found if @deal.blank?
    return render_not_found(:forbidden) if !current_user.admin?

  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end

  def update
    @deal = Deal.friendly.find(params[:id])
    return render_not_found if @deal.blank?
    return render_not_found(:forbidden) if !current_user.admin?

    @deal.update_attributes(deal_params)
    
    if @deal.valid?
      redirect_to admin_deals_path
    else
      render :edit, status: :unprocessable_entity
    end 
  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end


  def destroy
    @deal = Deal.friendly.find(params[:id])
    return render_not_found if @deal.blank?
    return render_not_found(:forbidden) if !current_user.admin?
    @deal.destroy

    redirect_to admin_deals_path

  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end


  private

  def deal_params
    params.require(:deal).permit(:title, :message, :deeplink, :picture, :retailer_id, {deal_ids: []}, 
      :category_id, :gender_id, :subcategory_id, :starts, :ends, :code, :terms)
  end

  
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy, :edit_multiple, :update_multiple]

	def index
		if params[:gender].present?
			@gender = Gender.find_by_name(params[:gender])
			@deals = []
			@gender.categories.each do |cat|
				cat.subcategories.each do |sub|
					sub.deals.order(:created_at).each do |deal|
						@deals << deal
					end
				end
			end

		else
			@deals = Deal.order(created_at: :desc)
		end
	end

	def show
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def men
		@gender = Gender.find_by_name("men")
		@deals = @gender.deals
		render :index
	end

	def women
		@gender = Gender.find_by_name("women")
		@deals = @gender.deals
		render :index
	end

	def beauty
		@gender = Gender.find_by_name("beauty")
		@deals = @gender.deals
		render :index
	end
	
	def new
		@deal = Deal.new
	end

	def create
		@deal = current_user.deals.create(deal_params)
		if @deal.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user

	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def update
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user

		@deal.update_attributes(deal_params)
		
		if @deal.valid?
			redirect_to root_path
		else
			render :edit, status: :unprocessable_entity
		end 
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end


	def destroy
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user
		@deal.destroy

		redirect_to root_path

	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def subcategory_options
	    @subcategories = Gender.find(params[:gender]).subcategories
	    @categories = Hash.new

	     render json: @subcategories, :only => [:id, :name]
  	end

	private

	def deal_params
		params.require(:deal).permit(:title, :message, :deeplink, :picture, :retailer_id, {deal_ids: []}, 
			:category_id, :gender_id, :subcategory_id, :starts, :ends, :code, :terms, :gender)
	end
end

app/helpers/admin/deals_helper.rb
module Admin::DealsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_deal_card.html.erb
<div class="card">
	<header class="card-header"></header>
	<%= link_to deal.deeplink, 'data-gtm-event' => 'dealClicked', 'data-gtm-variable' => "#{deal.retailer.name}", :target => "_blank" do %>
		<div class="card-image">
			<div class="card-image-inner">
				<figure id="deal-card-image">
				<%= image_tag deal.picture.present? ? deal.picture : 'deal_image_holder.png', :class => 'deal_image', alt: "#{deal.retailer.name} deal image" %>
				</figure>
			</div>
				<div class="cta-layer">
					<div class='deal-logo'>
						<% if deal.retailer.logo.present? %>
							<%= image_tag deal.retailer.logo, alt: "#{deal.retailer.name} logo" %>
						<% end %>
					</div>
					<div class='cta-layer-inner'>
						<div class="card-header-title deal-header-title">
							<div>
								<span class="is-blue-highlight"><%= deal.title %></span>
							</div>
						</div>
						<div class="level is-mobile">
							<button class="button cta-button is-pink-button level-item">
								Get this Deal Now
							</button>
						</div>
					</div>
				</div>
		</div>
	<% end %>
	<div class="card-content">
		<div class="open-message"><%= deal.message.html_safe %>
		<br />
		<br />
			<p class="center">check out <%= link_to "this deal", deal_path(deal), :class => "is-blue-highlight" %> from <%= link_to deal.retailer.name, retailer_path(deal.retailer), :class => "highlight" %></p>
		</div>
	</div>
</div>

app/views/deals/_expired_deal_card.html.erb
<div class="card">
    <a data-gtm-event='expiredDealClicked', data-gtm-variable= "#{deal.retailer.name}"></a>
      <div class="card-image">
        <div class="card-image-inner">
          <figure class="image is-16by9 expired-card-image" id="deal-card-image">
            <%= image_tag deal.picture.present? ? deal.picture : 'deal_image_holder.png', :class => 'deal_image', alt: "#{deal.retailer.name} deal image" %>
          </figure>
          <div class='cta-layer'>
            <div class='deal-logo'>
              <% if deal.retailer.logo.present? %>
                <%= image_tag deal.retailer.logo, alt: "#{deal.retailer.name} logo" %>
              <% end %>
            </div>        
            <div class="deal-header-expired-title">
              <div>
              <span class="is-blue-highlight"><%= deal.title %></span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-banner is-pink level is-mobile">
        <span class="level-item">Deal Expired</span>
      </div>
    <div class="card-content">
      <div class="message"><%= deal.message.html_safe %>
        <p class="center">check out <%= link_to "this deal", deal_path(deal), :class => "highlight" %> from <%= link_to deal.retailer.name, retailer_path(deal.retailer), :class => "highlight" %></p>
      </div>
      <div class="has-text-centered more-click">
        <a data-gtm-event='expiredDealShowMoreClicked', data-gtm-variable = "#{deal.retailer}">Show More</a></div>
    </div>
</div>

app/views/deals/_new_deal.html.erb
<%= simple_form_for Deal.new do |f| %>
  <%= f.input :title, wrapper: :horizontal_input %>
  <%= f.input :picture, wrapper: :horizontal_input %>
  <%= f.input :message, input_html: {class: 'textarea'}, wrapper: :horizontal_input  %>

  <%= f.input :gender_id, label: 'Type', collection: Gender.all, value_method: :id, wrapper: :horizontal_select, input_html: {class: 'gender-type', 'data-url' => subcategory_options_url } %>

  <%= f.input :subcategory_id, label: "category", collection: Subcategory.all, wrapper: :horizontal_select, input_html: {class: 'subcategory-options'} %>
  <%= f.input :starts, as: :datetime, html5: true, wrapper: :horizontal_input, input_html: { type: "datetime-local", value: DateTime.now.strftime("%Y-%m-%dT%H:%M:%S") } %>
  <%= f.input :ends, as: :datetime, html5: true, wrapper: :horizontal_input, input_html: { type: "datetime-local"}%>
  <%= f.input :deeplink, wrapper: :horizontal_input, input_html: { id: "deeplink", 'data-url' => get_article_path } %>
  <%= f.input :retailer_id, collection: Retailer.all.order(:name), wrapper: :horizontal_select %>
  <br class='is-clearfix'/>
  <%= f.submit "Add", class: "button is-medium is-success" %>
<% end %>


<!-- <script>
  $(document).ready(function() {
    $("#deeplink").on("paste", function(){
      setTimeout(function() {
        link = $("#deeplink").val();
        postUrl = $("#deeplink").attr('data-url');
        console.log(link);
        console.log(postUrl);
    //     $("#thumbs").html("<p>loading</p>");
    //     var postData = {
    //       'url' : $("#link").val()
    //       };
        $.ajax({
             type: "GET",
             url: postUrl,
             data: {posting: {url: link} }, //assign the var here 
             success: function(msg){
              console.log(msg);
             }
            // $("#thumbs").html( "Data Saved: " + msg );
            //     $(".thumb").click(function(){
            //     (this).attr('id');


            });

    //          }

    //     });
      }, 500);
    });

  })
</script> -->

app/views/deals/edit.html.erb
<h1>Edit <%= @retailer.name %></h1>

<%= simple_form_for @deal do |f| %>
	<%= f.input :title %>
	<%= f.input :picture %>
	<%= f.input :message %>
	<%= f.input :deeplink %>
	<%= f.input :retailer_id, collection: Retailer.all %>
	<%= f.submit "Post" %>
<% end %>

app/views/deals/edit_multiple.html.erb
<h1>Edit Deals</h1>

<%= form_tag update_multiple_deals_path do %>
	<table class="multiple-edit">

		<% @deals.each do |deal| %>
			<%= simple_fields_for "deals[]", deal do |f| %>
			<tr>
				<td><%= f.input :title %></td>
				<td><%= f.input :message %></td>
			</tr>
			<tr>
				<td>					
					<%= f.input :picture %>
					<%= deal.picture %>
					</td>
				<td><%= f.input :deeplink %>
				<%= f.input :retailer_id, label: "Retailers", collection: Retailer.all %></td>
			</tr>
			<% end %>
		<% end %>
	</table>
	<%= link_to 'Cancel', deals_path, class: "butotn" %> 
	<%= submit_tag "Post" %>
<% end %>

app/views/deals/index.html.erb
<% if @gender.present? %>
<h1><%= @gender.name.capitalize %></h1>
	<p><%= @gender.description %></p>
<% end %>

<section class="hero is-transparent is-bold">
    <%= render :partial => 'layouts/hero' %>
</section>

<% if current_user %>
  <section>
      <div class="container">
        <button id="new-deal-modal-button" class="button is-danger is-outlined">Add a new deal</button>

      <div class="modal" id="new-deal-modal" aria-labelledby="modal-title" role="dialog" aria-hidden="true">
        <div class="modal-background"></div>
        <div role="document" class="modal-content">
            <h2 class="title is-2">Add a new deal</h2>
            <%= render :partial => '/deals/new_deal' %>
        </div>
        <button class="modal-close" aria-label="Close this dialog window"></button>
      </div>
    </div>
  </section>
  <br />
<% end %>

<section>
  <div class="container">
    <div class="columns">
      <div class="column is-half is-offset-one-quarter">
          <% @deals.each do |deal| %>
            <div class="column is-10 <%= cycle('','is-offset-4') %>">
              <% if deal.ends.present? %>
                <% if deal.ends > Time.zone.today %>
            		  <%= render :partial => '/deals/deal_card', :locals => {:deal => deal} %>
                <% else %>
                  <%= render :partial => '/deals/expired_deal_card', :locals => {:deal => deal} %>
                <% end %>
              <% else %>
                <%= render :partial => '/deals/deal_card', :locals => {:deal => deal} %>
              <% end %>
            </div>
            <% end %>
      </div>
    </div>
  </div>
</section>

<script>
  $(document).ready(function() {
    $('#new-deal-modal-button').click(function() {
      $('#new-deal-modal').addClass('is-active')
    })
    $('.modal-close').click(function() {
      $('#new-deal-modal').removeClass('is-active')
    })
    $('.modal-background').click(function() {
      $('#new-deal-modal').removeClass('is-active')
    })
  });
</script>

app/views/deals/new.html.erb
<h1 class="title is-1">Add new deal</h1>

<%= render :partial => '/deals/new_deal' %>

<br />
<br />

app/views/deals/show.html.erb
<%= link_to 'Check out other deals', deals_path, :class => 'feed-button btn' %>
<br />

<%= render :partial => '/deals/deal_card', :locals => {:deal => @deal} %>