config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "feeds#index"

  get :privacy_policy, to: "static_pages#privacy_policy"
  get :contact, to: "static_pages#contact"
  post :messages, to: 'static_pages#messages'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get :subcategory_options, to: "deals#subcategory_options"

  resources :feeds, only: [:index]
  resources :deals do
    resources :comments, only: :create
  end

    get :men, to: "deals#men"
    get :women, to: "deals#women"
    get :beauty, to: "deals#beauty"

  resources :retailers, only: [:index, :show] do
    collection do
      post :import
    end
  end

  resources :articles, only: [:index, :create]
  get :get_article, to: "articles#get_article"

  namespace :admin do
    resources :deals do
      collection do
        post :import
        get :edit_multiple
        put :update_multiple
      end
    end
    resources :retailers do
      collection do
        post :import
      end
    end
    resources :publishers do
    end
  end

end

app/models/deal.rb
class Deal < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	validates :title, :message, :deeplink, presence: true
	validates :picture, presence: true

	belongs_to :user
	belongs_to :retailer
	belongs_to :subcategory
	belongs_to :gender

	has_many :comments

	acts_as_xlsx

	scope :from_now, -> { self.where('starts >= ?', DateTime.now) }

	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item = find_by_id(row["id"]) || new
			item.attributes = row.to_hash.slice(*self.column_names)
			# item.title = "#{item.advertiser} #{item.starts.strftime('%d-%m-%Y')}" if item.starts.present?
			item.save!
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :deals
  has_many :articles

end

app/controllers/admin/deals_controller.rb
class Admin::DealsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

  def index
    @deals = Deal.all
    respond_to do |format|
        format.html
        format.csv { send_data @deals.to_csv, filename: "deals-#{Date.today}.csv"}
        format.xlsx
    end
  end

	def import
      Deal.import(params[:file])
      flash[:notice] = 'File has been imported'
      redirect_to admin_deals_path
    end
    
	def edit_multiple
     	@deals = Deal.where(id: deal_params[:deal_ids])
     	return render_not_found if @deals.blank?
     	return render_not_found(:forbidden) if !current_user.admin?
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def update_multiple
		@deals = Deal.friendly.update(params[:deals].keys, params[:deals].values)
		return render_not_found(:forbidden) if !current_user.admin?
		
		@deals.reject! { |deal| deal.errors.empty? }
		if @deals.empty?
			redirect_to admin_deals_path
		else
			render "edit_multiple"
		end
	end

  def new
    @deal = Deal.new
  end

  def create
    @deal = current_user.deals.create(deal_params)
    if @deal.valid?
      redirect_to admin_deals_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @deal = Deal.friendly.find(params[:id])
    return render_not_found if @deal.blank?
    return render_not_found(:forbidden) if !current_user.admin?

  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end

  def update
    @deal = Deal.friendly.find(params[:id])
    return render_not_found if @deal.blank?
    return render_not_found(:forbidden) if !current_user.admin?

    @deal.update_attributes(deal_params)
    
    if @deal.valid?
      redirect_to admin_deals_path
    else
      render :edit, status: :unprocessable_entity
    end 
  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end


  def destroy
    @deal = Deal.friendly.find(params[:id])
    return render_not_found if @deal.blank?
    return render_not_found(:forbidden) if !current_user.admin?
    @deal.destroy

    redirect_to admin_deals_path

  rescue ActiveRecord::RecordNotFound
    return render_not_found
  end


  private

  def deal_params
    params.require(:deal).permit(:title, :message, :deeplink, :picture, :retailer_id, {deal_ids: []}, 
      :category_id, :gender_id, :subcategory_id, :starts, :ends, :code, :terms)
  end

  
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy, :edit_multiple, :update_multiple]

	def index
		if params[:gender].present?
			@gender = Gender.find_by_name(params[:gender])
			@deals = []
			@gender.categories.each do |cat|
				cat.subcategories.each do |sub|
					sub.deals.order(:created_at).each do |deal|
						@deals << deal
					end
				end
			end

		else
			@deals = Deal.order(created_at: :desc)
		end
	end

	def show
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def men
		@gender = Gender.find_by_name("men")
		@deals = @gender.deals
		render :index
	end

	def women
		@gender = Gender.find_by_name("women")
		@deals = @gender.deals
		render :index
	end

	def beauty
		@gender = Gender.find_by_name("beauty")
		@deals = @gender.deals
		render :index
	end
	
	def new
		@deal = Deal.new
	end

	def create
		@deal = current_user.deals.create(deal_params)
		if @deal.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user

	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def update
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user

		@deal.update_attributes(deal_params)
		
		if @deal.valid?
			redirect_to root_path
		else
			render :edit, status: :unprocessable_entity
		end 
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end


	def destroy
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user
		@deal.destroy

		redirect_to root_path

	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def subcategory_options
	    @subcategories = Gender.find(params[:gender]).subcategories
	    @categories = Hash.new

	     render json: @subcategories, :only => [:id, :name]
  	end

	private

	def deal_params
		params.require(:deal).permit(:title, :message, :deeplink, :picture, :retailer_id, {deal_ids: []}, 
			:category_id, :gender_id, :subcategory_id, :starts, :ends, :code, :terms, :gender)
	end
end

app/helpers/admin/deals_helper.rb
module Admin::DealsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/admin/deals/edit.html.erb
<h1>Edit Deal</h1>

<%= simple_form_for @deal do |f| %>
  <%= f.input :title, wrapper: :horizontal_input %>
  <%= f.input :picture, wrapper: :horizontal_input %>
  <%= f.input :message, input_html: {class: 'textarea'}, wrapper: :horizontal_input  %>

  <%= f.input :gender_id, label: 'Type', collection: Gender.all, value_method: :id, wrapper: :horizontal_select, input_html: {class: 'gender-type', 'data-url' => subcategory_options_url } %>

  <%= f.input :subcategory_id, label: "category", collection: @deal.gender.subcategories, wrapper: :horizontal_select, input_html: {class: 'subcategory-options'} %>
  <%= f.input :starts, as: :datetime, html5: true, wrapper: :horizontal_input, input_html: { type: "datetime-local", value: DateTime.now.strftime("%Y-%m-%dT%H:%M:%S") } %>
  <%= f.input :ends, as: :datetime, html5: true, wrapper: :horizontal_input, input_html: { type: "datetime-local"}%>
  <%= f.input :deeplink, wrapper: :horizontal_input %>
  <%= f.input :retailer_id, collection: Retailer.all.order(:name), wrapper: :horizontal_select %>
  <br class='is-clearfix'/>
  <%= f.submit "Add", class: "horizontal-button button is-medium is-primary is-pulled-right" %>
<% end %>

app/views/admin/deals/edit_multiple.html.erb
<h1>Edit Deals</h1>

<%= form_tag update_multiple_admin_deals_path, method: 'put' do %>
	<table class="multiple-edit">

		<% @deals.each do |deal| %>
			<%= simple_fields_for "deals[]", deal do |f| %>
			<tr>
				<td class="image-td">
					<%= image_tag deal.picture, class: 'table-image' %>
				</td>
				<td>
					<%= f.input :title, wrapper: :horizontal_input  %>
					<%= f.input :deeplink, wrapper: :horizontal_input %>
					<%= f.input :retailer_id, label: "Retailers", collection: Retailer.all, wrapper: :horizontal_input %>
					<%= f.input :gender_id, label: 'Type', collection: Gender.all, value_method: :id, wrapper: :horizontal_select, input_html: {class: 'gender-type', 'data-url' => subcategory_options_url } %>
					<%= f.input :subcategory_id, label: "category", collection: Subcategory.all, wrapper: :horizontal_select, input_html: {class: 'subcategory-options'} %>
					<%= f.input :picture, wrapper: :horizontal_input %>
					<%= f.input :slug, wrapper: :horizontal_input %>
				</td>
				<td><%= f.input :message, input_html: {class: 'message-box'} %>
				<%= f.input :starts, as: :datetime, html5: true, wrapper: :horizontal_input %>
  			<%= f.input :ends, as: :datetime, html5: true, wrapper: :horizontal_input %>
  			</td>

				</tr>
			<% end %>
		<% end %>
	</table>
	<%= link_to 'Cancel', deals_path, class: "button" %> 
	<%= submit_tag "Update" %>
<% end %>

<script>
	$(document).ready(function() {
		$('.gender-type').change(function() {
			selection = $(this).val();
			genderInput = $(this)
			genderInput.parent().next().children('.subcategory-options').empty().append('<option value=""></option>');
			console.log(selection);
			$.ajax({
				type: 'GET',
				url: "<%= subcategory_options_admin_deals_path %>",
				dataType: "text",
				data: "gender=" + selection
			}).done(function(data) {
				console.log(genderInput.parent().next().children('.subcategory-options').val());
				$.each(JSON.parse(data), function(index, element) {
						genderInput.parent().next().children('.subcategory-options').append($('<option>', {
							value: parseInt(element.id),
							text: element.name
						}));						
				})
			})
		})
	})
</script>

app/views/admin/deals/index.html.erb
<div class="container">
  <h1 class='title is-1'>Admin</h1>

  <div class="columns">
    <div class="column">
      <h3 class='title is-3'>Tools</h3>
      <table class="table">
        <tbody>
          <tr>
            <td>Export <%= link_to "CSV", admin_deals_path(format: 'csv'), class: "button is-small is-success" %> | <%= link_to "Excel", deals_path(format: 'xlsx'), class: "button is-small is-success" %></td>
          </tr>
          <tr>
            <td><%= link_to 'New Deal', new_admin_deal_path, class: 'button is-success' %></td>
          </tr>
          <tr>
            <td>
               <button id="multi-deal-modal-button" class="button is-success">Edit Multiple Deals</button>
            </td>
          </tr>
          <tr>
            <td>
              <div>
                <%= form_tag import_admin_deals_path, multipart: true do %>
                  <%= file_field_tag :file, accept: 'text/csv' %>
                  <%= submit_tag "Import Deals", class: 'button is-success' %>
                <% end %>
              </div>      
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="column">
      <strong>Messages:</strong><%= Message.count %> <br />
      <strong>Subcategories:</strong> <%= Subcategory.count %>
    </div>
  </div>  
   

  <div class="modal" id="multi-deal-modal" aria-labelledby="modal-title" role="dialog" aria-hidden="true">
    <div class="modal-background"></div>
    <div role="document" class="modal-content">
        <h2 class="title is-2">Edit Multiple Deals</h2>

        <p>Select multiple deals to edit</p>
        <%= form_tag edit_multiple_admin_deals_path, method: :get do %>
          <table class='table'>
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
              </tr>
            </thead>
            <tbody>
              <% @deals.each do |deal| %>
                <%= simple_fields_for "deals[]" do |f| %>
                <tr>
                  <td><%= check_box_tag 'deal[deal_ids][]', deal.id, checked = false, {id: dom_id(deal), :class => 'checkbox'} %>
                  <td><%= deal.title %></td>
                </tr>
                <% end %>
              <% end %>
              </tbody>
          </table>
          <%= submit_tag "Edit Multiple", class: 'button is-success' %>
        <% end %>

    </div>
    <button class="modal-close" aria-label="Close this dialog window"></button>
  </div>

  <div class="columns">
    <table class="table">
      <thead>
        <td>Title</td>
        <td>Shop</td>
        <td>Days</td>
        <td>Clicks</td>
      </thead>
      <tbody>
        <% @deals.each do |deal| %>
          <tr>
            <td><%= link_to deal.title, edit_admin_deal_path(deal) %></td>
            <td><%= deal.retailer.name %></td>
            <td><%= DateTime.now.to_date - deal.created_at.to_date %></td>
            <td></td>
          </tr>
        <% end%>
      </tbody>
    </table>
  </div>

  <br />
</div>


<script>
$(document).ready(function() {
  $('#multi-deal-modal-button').click(function() {
      $('#multi-deal-modal').addClass('is-active')
    })
    $('.modal-close').click(function() {
      $('#multi-deal-modal').removeClass('is-active')
    })
    $('.modal-background').click(function() {
      $('#multi-deal-modal').removeClass('is-active')
    })
})
</script>

app/views/admin/deals/messages.html.erb
<div class="container">
  <h3 class='title is-3'>Messages</h3>
  <table class="table">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Subject</th>
        <th>Message</th>
      </tr>
    <% @messages.each do |message| %> 
      <tr>
        <td><%= message.name %></td>
        <td><%= message.email %></td>
        <td><%= message.subject %></td>
        <td><%= message.message %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/deals/new.html.erb
<div class="container">
	<h1 class="title is-1">Add new deal</h1>

	<%= render :partial => '/deals/new_deal' %>
	<br />
	<br />
</div>

app/views/admin/deals/subcat.html.erb
<h3>Subcategories</h3>
<table>
  <tr>
    <th>Sub ID</th>
    <th>Name</th>
  </tr>
  <% @subcategories.each do |sub| %>
  <tr>
    <td><%= sub.id %></td>
    <td><%= sub.name %></td>
  </tr>
  <% end %>
</table>