config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "feeds#index"

  get :privacy_policy, to: "static_pages#privacy_policy"
  get :contact, to: "static_pages#contact"
  post :messages, to: 'static_pages#messages'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get :subcategory_options, to: "deals#subcategory_options"

  resources :feeds, only: [:index]
  resources :deals do
    resources :comments, only: :create
  end

    get :men, to: "deals#men"
    get :women, to: "deals#women"
    get :beauty, to: "deals#beauty"

  resources :retailers, only: [:index, :show] do
    collection do
      post :import
    end
  end

  resources :articles, only: [:index, :create]
  get :get_article, to: "articles#get_article"

  namespace :admin do
    resources :deals do
      collection do
        post :import
        get :edit_multiple
        put :update_multiple
      end
    end
    resources :retailers do
      collection do
        post :import
      end
    end
    resources :publishers do
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :gender

  acts_as_taggable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :retailers
  belongs_to :gender
  has_many :subcategories

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :deal
	belongs_to :user
end

app/models/deal.rb
class Deal < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	validates :title, :message, :deeplink, presence: true
	validates :picture, presence: true

	belongs_to :user
	belongs_to :retailer
	belongs_to :subcategory
	belongs_to :gender

	has_many :comments

	acts_as_xlsx

	scope :from_now, -> { self.where('starts >= ?', DateTime.now) }

	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item = find_by_id(row["id"]) || new
			item.attributes = row.to_hash.slice(*self.column_names)
			# item.title = "#{item.advertiser} #{item.starts.strftime('%d-%m-%Y')}" if item.starts.present?
			item.save!
		end
	end
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  has_many :categories
  has_many :subcategories, through: :categories
  has_many :deals
  has_many :articles
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
end

app/models/retailer.rb
class Retailer < ActiveRecord::Base
	has_many :deals
	has_and_belongs_to_many :categories

	validates :name, presence: true
	validates :host_url, presence: true
	validates :brief_description, presence: true

	mount_uploader :favicon, PictureUploader
	mount_uploader :logo, PictureUploader
	mount_uploader :cover, PictureUploader

	extend FriendlyId
	friendly_id :name, use: :slugged


	acts_as_xlsx


	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item = find_by_id(row["id"]) || new
			item.attributes = row.to_hash.slice(*self.column_names)
			next if item.name.nil? || item.host_url.nil? || item.brief_description.nil?
			item.save!
			item.update_attributes(category_ids: row["category_ids"]) if row["category_ids"].present?
		end
	end
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :deals

  acts_as_xlsx

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      item = find_by_id(row["id"]) || new
      item.attributes = row.to_hash.slice(*self.column_names)
      item.save!
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :deals
  has_many :articles

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, only: [:get_article]

	def index
		@articles = Article.order(created_at: :desc)
	end

	def get_article
		@url = article_params[:url]
		@article = ArticleCrawler.new(@url)

		respond_to :js
	end

	def create
		if Article.exists?(title: article_params[:title])
			@article = Article.find_by_title(article_params[:title])
		else
			@article = current_user.articles.create(article_params)
		end

		redirect_to articles_path
	end

	private

	def article_params
		params.require(:article).permit(:title, :url, :description, :publisher, :image_url)
	end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy, :edit_multiple, :update_multiple]

	def index
		if params[:gender].present?
			@gender = Gender.find_by_name(params[:gender])
			@deals = []
			@gender.categories.each do |cat|
				cat.subcategories.each do |sub|
					sub.deals.order(:created_at).each do |deal|
						@deals << deal
					end
				end
			end

		else
			@deals = Deal.order(created_at: :desc)
		end
	end

	def show
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def men
		@gender = Gender.find_by_name("men")
		@deals = @gender.deals
		render :index
	end

	def women
		@gender = Gender.find_by_name("women")
		@deals = @gender.deals
		render :index
	end

	def beauty
		@gender = Gender.find_by_name("beauty")
		@deals = @gender.deals
		render :index
	end
	
	def new
		@deal = Deal.new
	end

	def create
		@deal = current_user.deals.create(deal_params)
		if @deal.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user

	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def update
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user

		@deal.update_attributes(deal_params)
		
		if @deal.valid?
			redirect_to root_path
		else
			render :edit, status: :unprocessable_entity
		end 
	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end


	def destroy
		@deal = Deal.friendly.find(params[:id])
		return render_not_found if @deal.blank?
		return render_not_found(:forbidden) if @deal.user != current_user
		@deal.destroy

		redirect_to root_path

	rescue ActiveRecord::RecordNotFound
		return render_not_found
	end

	def subcategory_options
	    @subcategories = Gender.find(params[:gender]).subcategories
	    @categories = Hash.new

	     render json: @subcategories, :only => [:id, :name]
  	end

	private

	def deal_params
		params.require(:deal).permit(:title, :message, :deeplink, :picture, :retailer_id, {deal_ids: []}, 
			:category_id, :gender_id, :subcategory_id, :starts, :ends, :code, :terms, :gender)
	end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

	def index
		get_feed

		@feed_items = Kaminari.paginate_array(@items).page(params[:page]).per(10)
	end

	private

	def get_feed
		if @feed_items.nil?
			deals = Deal.order(created_at: :desc)
			articles = Article.order(created_at: :desc)

			@items = []
			@items += deals
			@items += articles
			@items.shuffle!
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer-logo">
    <%= link_to image_tag("Fash-logomark.png", alt: "logo image"), root_path, class: "mobile-logo" %>
</div>
  <a href="javascript:void(0)">About</a>
    <p>Looking for Fashion? We've got the steals. Browser the latest fashion deals and discounts</p>
  <%= link_to "Contact", contact_path %>
  <%= link_to "Privacy Policy", privacy_policy_path %>
  <% if current_user.try(:admin?) %>
  <%= link_to 'Admin', admin_deals_path %>
  <% end %>
  <%= link_to 'Sitemap', sitemap_url %>

app/views/layouts/_header.html.erb
  <nav role="navigation" id='fashsteal-nav' class="nav grad has-shadow level">

        <div class="level-item">
          <%= link_to image_tag("Fash-black-transp4x.png", alt: "logo image"), root_path, class: "logo is-hidden-mobile", 'data-gtm-event' => "logoClicked" %>
          <%= link_to image_tag("fash-logomark-black-transp.png", alt: "logo image"), root_path, class: "mobile-logo is-hidden-tablet" %>
        </div>

        <%= link_to 'Men', men_path, class: "level-item is-tab is-hidden-mobile", 'data-gtm-event' => "menClicked" %>
        <%= link_to 'Women', women_path, class: "level-item is-tab is-hidden-mobile", 'data-gtm-event' => "womenClicked" %>
        <%= link_to 'Beauty', beauty_path, class: "level-item is-tab is-hidden-mobile", 'data-gtm-event' => "beautyClicked" %>
        <a class="level-item is-tab is-hidden-mobile" id="shop-dropdown" data-gtm-event="shopsClicked">
            Shops</a>
              <ul class="dropdown is-pink" id="drop-menu">
                <li><%= link_to 'All', retailers_path %></li>
                <% @retailer_categories.each do |category| %>
                  <li><%= link_to category, retailers_path(category: category), class: "nav-item", 'data-gtm-event' => "#{category}Clicked" %></li>
                <% end %>
              </ul>

        <!-- This "nav-toggle" hamburger menu is only visible on mobile -->
        <!-- You need JavaScript to toggle the "is-active" class on "nav-menu" -->
        <span class="nav-toggle">
          <span></span>
          <span></span>
          <span></span>
        </span>

      <div  id="nav-hamburger" class="nav-right nav-menu">
        <%= link_to 'Men', men_path, class: "nav-item is-tab is-hidden-tablet", 'data-gtm-event' => "menClicked" %>
        <%= link_to 'Women', women_path, class: "nav-item is-tab is-hidden-tablet", 'data-gtm-event' => "womenClicked" %>
        <%= link_to 'Beauty', beauty_path, class: "nav-item is-tab is-hidden-tablet", 'data-gtm-event' => "beautyClicked" %>
        <%= link_to 'Shops', retailers_path, class: "nav-item is-tab is-hidden-tablet", 'data-gtm-event' => "shopsClicked" %>
      </div>

  </nav>

<script>
  $(document).ready(function() {
    $('.nav-toggle').click(function() {
      $('#nav-hamburger').toggleClass('is-active');
    });

    $('#shop-dropdown').click(function() {
      $('#drop-menu').toggleClass('is-open');
    });
  })
</script>

app/views/layouts/_hero.html.erb
  <div class="hero-body">
    <div class="container">
      <h2 class="subtitle">
        Come for the fashion deals and check out the latest style advice. <strong>FashSteals.com</strong> is your fashion source. Here you will find deals and discounts on the latest clothing, accessories, cosmetics and skincare products at the hottest brands.
      </h2>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FashSteals - Browse the latest fashion deals and discounts</title>
  <meta property="og:description" content="Looking for Fashion? We've got the steals. Get your latest fashion advice and browse the latest fashion deals & discounts" />
  <meta property="og:title" content="Your latest fashion source - FashSteals" />
  <meta property="description" content="Looking for Fashion? We've got the steals. Browse the latest fashion deals and discounts" />

  <meta property="og:image" content="/card-deck.png" />
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <meta name="theme-color" content="#ffffff">
  <%= favicon_link_tag(source='favicon.ico') %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="verification" content="70d3afe3ca46f1a43f7ac88b3699da73" />
  <meta name="google-site-verification" content="Hn_edsLIpU3gqsBtBeB4XAsdZg9EXRVE3IkK2FIfZuU" />
  <%= csrf_meta_tags %>
</head>
<body class=<%= '' if !controller.class.parents.include?(Admin) %>>
<%= google_tag_manager %>

<header class="<%= 'yellow' if controller.class.parents.include?(Admin) %>" role="banner">
  <%= render 'layouts/header' %>
</header>

<div class="body-container">

  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
    <br />
    <br />
  <% end %>
  <% if alert.present? %>
    <p class="alert"><%= alert %></p>
    <br />
    <br />
  <% end %>
	 <%= yield %>

</div>

<footer class="footer sticky" role="contentinfo">
  <div class="container">
    <div class="content has-text-centered">
      <%= render 'layouts/footer' %>
    </div>
  </div>
</footer>

</body>
</html>